prompts = ["x", "Hi"]
data_dir = "website/data"
log_level = "INFO"

[api]
max_retries = 8
max_cost_mtok = 30
temperature = 1.0
max_workers = 30
top_logprobs_openrouter_default = 20
timeout = 10
abandon_after = 100
openrouter_avoid_free_endpoints = true

[api.top_logprobs_openrouter]
fireworks = 5
azure = 5
inference-net = 5
xai = 8

[bi]
data_dir = "data_bi"

[bi.phase_1]
queries_per_token = 5
requests_per_second_per_endpoint = 5
tokens_per_endpoint = 400
chunk_size = 50
