prompts = ["x", "Hi"]
data_dir = "data"

[api]
max_retries = 15
max_workers = 60
top_logprobs_openrouter_default = 20
timeout = 30

[api.top_logprobs_openrouter]
fireworks = 5
azure = 5
inference-net = 5
xai = 8
